version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/services/oidc"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/services/postgres"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/services/wiremock"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/examples"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
